apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 788692874122.dkr.ecr.ap-northeast-1.amazonaws.com/test:latest
        ports:
        - containerPort: 80
