apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mynginx
  template:
    metadata:
      labels:
        run: mynginx
    spec:
      containers:
      - image: 879873534644.dkr.ecr.ap-northeast-1.amazonaws.com/eks-test:1.3
        name: mynginx
        ports:
        - containerPort: 80
